# Generated by Django 3.0.7 on 2020-07-06 13:17

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobile_number', models.CharField(max_length=11, unique=True, validators=[users.models.validate_mobile_number], verbose_name='شماره همراه')),
                ('gender', models.CharField(choices=[('m', 'آقای'), ('f', 'خانم')], default='m', max_length=1, verbose_name='جنسیت')),
                ('father_name', models.CharField(blank=True, default='', max_length=30, verbose_name='نام پدر')),
                ('melli_code', models.CharField(blank=True, max_length=10, validators=[users.models.validate_melli_code], verbose_name='کد ملی')),
                ('phone_number', models.CharField(blank=True, default='', max_length=11, validators=[users.models.validate_phone_number], verbose_name='تلفن ثابت')),
                ('workplace_number', models.CharField(blank=True, default='', max_length=11, validators=[users.models.validate_phone_number], verbose_name='تلفن محل کار')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('province', models.CharField(blank=True, default='', max_length=40, verbose_name='استان')),
                ('city', models.CharField(blank=True, default='', max_length=40, verbose_name='شهر')),
                ('address', models.CharField(blank=True, default='', max_length=100, verbose_name='نشانی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
