# Generated by Django 2.2 on 2021-01-18 10:27

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201115_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, validators=[users.models.validate_phone_number], verbose_name='شماره منزل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='workplace_number',
            field=models.CharField(blank=True, default='', max_length=11, validators=[users.models.validate_phone_number], verbose_name='شماره ضروری'),
        ),
    ]
