# Generated by Django 2.2 on 2021-04-17 09:52

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.CharField(choices=[('0', 'بی سواد'), ('1', 'ابتدایی'), ('2', 'سیکل'), ('3', 'دیپلم'), ('4', 'کاردانی'), ('5', 'کارشناسی'), ('6', 'کارشناسی ارشد'), ('7', 'دکتری'), ('8', 'علوم پزشکی')], default='0', max_length=1, verbose_name='سطح تحصیلات'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number_description',
            field=models.CharField(default=' ', max_length=30, verbose_name='عنوان تلفن ثابت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, validators=[users.models.validate_phone_number], verbose_name='شماره ثابت'),
        ),
    ]
