# Generated by Django 2.2 on 2021-04-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210417_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='education',
            field=models.CharField(choices=[('0', 'بی سواد'), ('1', 'ابتدایی'), ('2', 'سیکل'), ('3', 'دیپلم'), ('4', 'کاردانی'), ('5', 'کارشناسی'), ('6', 'کارشناسی ارشد'), ('7', 'دکتری'), ('8', 'علوم پزشکی'), ('9', 'تحصیلات حوزوی')], default='0', max_length=1, verbose_name='سطح تحصیلات'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number_description',
            field=models.CharField(blank=True, max_length=30, verbose_name='عنوان تلفن ثابت'),
        ),
    ]
