# Generated by Django 2.2 on 2021-06-13 08:19

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210510_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='melli_code',
            field=models.CharField(max_length=10, unique=True, validators=[users.models.validate_melli_code], verbose_name='کد ملی'),
        ),
    ]
