# Generated by Django 2.2 on 2021-09-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210912_1137'),
        ('users', '0010_auto_20210922_1110'),
    ]

    operations = [
    ]
