# Generated by Django 2.2 on 2021-09-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20210922_1325'),
        ('users', '0011_alter_user_first_name'),
    ]

    operations = [
    ]
