# Generated by Django 3.2.7 on 2021-10-11 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210922_1110'),
        ('users', '0011_alter_user_first_name'),
    ]

    operations = [
    ]
