# Generated by Django 2.2 on 2021-10-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20211002_1341'),
        ('users', '0010_auto_20210929_1322'),
    ]

    operations = [
    ]
