# Generated by Django 2.2 on 2021-10-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_merge_20211002_1419'),
        ('users', '0014_auto_20210928_1108'),
    ]

    operations = [
    ]
