# Generated by Django 2.2 on 2021-10-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20211011_0833'),
        ('users', '0015_merge_20211002_1442'),
    ]

    operations = [
    ]
