# Generated by Django 3.0.7 on 2020-11-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verify_customer', models.CharField(default='باسلام\nمتقاضی محترم پرونده شما تایید گردید. لطفا با مراجعه به فروشگاه برای تعیین زمان و دریافت پیش فاکتور اقدام نمایید.\n\nباتشکر\nفرامیران- مجری ارائه تسهیلات فروش اقساطی محصولات ایرانی', max_length=1000, verbose_name='پیامک تایید متقاضی')),
                ('reject_customer', models.CharField(default='باسلام\nمتقاضی محترم پرونده شما تایید نشد. لطفا با مراجعه به حساب کاربری خود نسبت به دلیل عدم تایید اطلاع یابید.\n\nباتشکر\nفرامیران- مجری ارائه تسهیلات فروش اقساطی محصولات ایرانی', max_length=1000, verbose_name='پیامک رد متقاضی')),
            ],
            options={
                'verbose_name': 'متن پیامک ها',
                'verbose_name_plural': 'متن پیامک ها',
            },
        ),
    ]
