# Generated by Django 3.0.7 on 2020-11-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0002_messagetext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetext',
            name='reject_customer',
            field=models.TextField(default='باسلام\nمتقاضی محترم پرونده شما تایید نشد. لطفا با مراجعه به حساب کاربری خود نسبت به دلیل عدم تایید اطلاع یابید.\n\nباتشکر\nفرامیران- مجری ارائه تسهیلات فروش اقساطی محصولات ایرانی', verbose_name='پیامک رد متقاضی'),
        ),
        migrations.AlterField(
            model_name='messagetext',
            name='verify_customer',
            field=models.TextField(default='باسلام\nمتقاضی محترم پرونده شما تایید گردید. لطفا با مراجعه به فروشگاه برای تعیین زمان و دریافت پیش فاکتور اقدام نمایید.\n\nباتشکر\nفرامیران- مجری ارائه تسهیلات فروش اقساطی محصولات ایرانی', verbose_name='پیامک تایید متقاضی'),
        ),
    ]
