# Generated by Django 3.0.7 on 2020-11-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0003_auto_20201109_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetext',
            name='balance_contract',
            field=models.TextField(default='با سلام\nمتقاضی محترم، نامه تسویه اقساط شما برای صندوق بین الملل ارسال شده است. لطفا هفته آینده با هماهنگی با واحد مالی صندوق بین الملل جهت دریافت اسناد ضمانت خود با مراجعه به دفتر صندوق اقدام فرمایید.\n\nشماره تماس: ۸۸۶۱۹۰۰۱ (امور مالی)\nنشانی : میدان شیخ بهایی ، خیابان سئول، بالاتر از بانك گردشگری، پلاك ۳۱ ،واحد سوم(طبقه اول)', verbose_name='پیامک تسویه قرارداد'),
        ),
        migrations.AddField(
            model_name='messagetext',
            name='notify_debit',
            field=models.TextField(default='با سلام\nمتقاضی محترم، قسط خرید لوام خانگی ایرانی شما معوق شده است؛ خواهشمند است، در اسرع وقت نسبت به تسویه آن اقدام و مراتب را به شماره واتس اپ یا تلگرام ۰۹۳۷۴۷۸۸۶۳۴ اطلاع دهید.\n\nاطلاعات اقساط شما:\nسررسید: {0} هر ماه\nشماره کارت اختصاصی شما: {1}\nمبلغ هر قسط: {2} ریال\n\nبا تشکر\nفرامیران- مجری ارائه تسهیلات فروش اقساطی محصولات ایرانی', verbose_name='پیامک بدهی'),
        ),
        migrations.AddField(
            model_name='messagetext',
            name='notify_instalment',
            field=models.TextField(default='با سلام\nمتقاضی محترم، تاریخ قسط {0}خرید لوازم خانگی ایرانی شما، {1} ماه است. لطفا نسبت به واریز به موقع خود اقدام فرمایید.\nارسال تصویر قبض واریز و کسب اطلاعات بیشتر به شماره واتساپ یا تلگرام زیر:\n۰۹۳۷۴۷۸۸۶۳۴\n\nبا تشکر\nفرامیران- مجری ارائه تسهیلات فروش اقساطی محصولات ایرانی', verbose_name='پیامک یادآوری اقساط'),
        ),
        migrations.AddField(
            model_name='messagetext',
            name='verify_contract',
            field=models.TextField(default='باسلام\nمتقاضی محترم، پرونده شما تایید شد. لطفا برای دریافت و ترخیص کالا به فروشگاه مراجعه نمایید.\n\nباتشکر\nفرامیران- مجری ارائه تسهیلات فروش اقساطی محصولات ایرانی', verbose_name='پیامک تایید قرارداد'),
        ),
    ]
