# Generated by Django 3.0.7 on 2020-11-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0005_auto_20201109_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetext',
            name='check_appointment',
            field=models.TextField(default='با سلام\nمتقاضی محترم، زمان مراجعه شما روز {0} ساعت {1} می باشد. لطفا با در دست داشتن اصل شناسنامه و کارت ملی و همچنین همراه داشتن چک صیاد به آدرس دفتر مراجعه نمایید.\n\nموقعیت شرکت فرامیران:\nجنت آباد جنوبی، خیابان چهارباغ شرقی، ۱۶ متری شمالی یکم، کوچه آذرشب، پلاک ۳۸/۱ واحد ۱۲\nhttps://goo.gl/maps/WFUk6g7MJk82 :لینک', verbose_name='پیامک قرارملاقات'),
        ),
    ]
