# Generated by Django 2.2 on 2020-12-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0006_auto_20201109_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetext',
            name='conditional_verify',
            field=models.TextField(default='باسلام\nمتقاضی محترم پرونده شما به صورت مشروط تایید گردید. برای مشاهده توضیحات به پنل فرامیران مراجعه نمایید. همچنین با مراجعه به فروشگاه برای تعیین مدارک و زمان عقد قرارداد و همچنین دریافت پیش فاکتور اقدام نمایید.\n\nباتشکر\nفرامیران- مجری ارائه تسهیلات فروش اقساطی محصولات ایرانی\n', verbose_name='پیامک تایید اعتبار مشروط'),
        ),
    ]
