# Generated by Django 2.2 on 2021-01-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0007_messagetext_conditional_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='IceToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300)),
                ('expire_date', models.DateTimeField()),
            ],
        ),
    ]
