# Generated by Django 2.2 on 2021-03-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0008_icetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetext',
            name='defect_documnet',
            field=models.TextField(default='متقاضی محترم فرامیران\nباسلام\nضمن ابراز خرسندی از پیوستن شما به خانواده بزرگ فرامیران، جهت تکمیل فرآیند ثبت نام و خرید، در پنل کاربری(http://faramiran.com/login) از بخش ویرایش نسبت به بارگذاری مدارک ذیل اقدام فرمایید.\n{0}\nدر صورت نیاز به پشتیبانی در ساعات ۹ تا ۱۶ با شماره 02146045218 تماس حاصل فرمایید.', verbose_name='پیامک نقص مدارک'),
        ),
        migrations.AddField(
            model_name='messagetext',
            name='expire_credit',
            field=models.TextField(default='متقاضی فرامیران\nبا سلام\nبه علت عدم مراجعه شما تاکنون رتبه اعتباری شما منقضی شده است.\nدر صورت نیاز به پشتیبانی در ساعات ۹ تا ۱۶ با شماره 02146045218 تماس حاصل فرمایید.', verbose_name='پیامک انقضای اعتبار'),
        ),
        migrations.AddField(
            model_name='messagetext',
            name='verify_supplier_contract',
            field=models.TextField(default='باسلام\nمتقاضی محترم، پرونده شما تایید شد. لطفا برای دریافت و ترخیص کالا به فروشگاه مراجعه نمایید.\n\nباتشکر\nفرامیران- مجری ارائه تسهیلات فروش اقساطی محصولات ایرانی', verbose_name='پیامک تایید قرارداد تامین کننده نوع۲'),
        ),
    ]
