# Generated by Django 2.2 on 2021-03-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0009_auto_20210301_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetext',
            old_name='defect_documnet',
            new_name='defect_document',
        ),
    ]
