# Generated by Django 2.2 on 2021-04-04 07:56

import OTP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0011_auto_20210404_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecode',
            name='mobile_number',
            field=models.CharField(max_length=11, validators=[OTP.models.validate_mobile_number], verbose_name='شماره همراه'),
        ),
    ]
