# Generated by Django 2.2 on 2021-08-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0013_messagetext_good_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetext',
            name='contract_permission_expire',
            field=models.TextField(default='متقاضی فرامیران\nباسلام\nبه دلیل عدم تکمیل مدارک پس از گذشت 14 روز از تاریخ عقد قرارداد شما، پرونده شما لغو شد.', verbose_name='پیامک لغو قرارداد'),
        ),
    ]
