# Generated by Django 2.2 on 2021-09-01 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0016_auto_20210823_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagetext',
            name='check_appointment',
        ),
    ]
