# Generated by Django 3.2.6 on 2021-09-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0020_alter_messagetext_mulct_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'متن ایمیل ',
                'verbose_name_plural': 'متن ایمیل ها',
            },
        ),
    ]
