# Generated by Django 3.2.6 on 2021-09-18 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0021_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='ET_appointment',
            field=models.TextField(default='قرارملاقات جدید برای متقاضی: {customer} \n در روز {date} زمان {time} \n نام تامین کننده: {supplier}', verbose_name='ایمیل قرار ملاقات'),
        ),
    ]
