# Generated by Django 3.2.6 on 2021-09-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0023_auto_20210918_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='ET_appointment',
            new_name='appointment_ET',
        ),
        migrations.RenameField(
            model_name='emails',
            old_name='ST_appointment',
            new_name='appointment_ST',
        ),
        migrations.AlterField(
            model_name='emails',
            name='ADMIN_EMAILS',
            field=models.TextField(default=' a.khoji2001@gmail.com , abolfazlkhojasteh2001@gmail.com', help_text='  جهت جداسازی ایمیل ها از {,} استفاده کنید', verbose_name='دریافت کنندگان ایمیل ها'),
        ),
    ]
