# Generated by Django 3.2.6 on 2021-09-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0024_auto_20210918_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emails',
            name='ADMIN_EMAILS',
        ),
        migrations.RemoveField(
            model_name='emails',
            name='appointment_ET',
        ),
        migrations.RemoveField(
            model_name='emails',
            name='appointment_ST',
        ),
        migrations.AddField(
            model_name='emails',
            name='ET',
            field=models.TextField(default='', verbose_name='متن ایمیل'),
        ),
        migrations.AddField(
            model_name='emails',
            name='ST',
            field=models.TextField(default='', verbose_name='عنوان ایمل'),
        ),
        migrations.AddField(
            model_name='emails',
            name='TO',
            field=models.TextField(default='', help_text='برای جداسازی از , استفاده کنید', verbose_name='دریافت کنندگان'),
        ),
        migrations.AddField(
            model_name='emails',
            name='bcc',
            field=models.TextField(default='', verbose_name='رونوشت مخفی'),
        ),
        migrations.AddField(
            model_name='emails',
            name='cc',
            field=models.TextField(default='', verbose_name='رونوشت'),
        ),
        migrations.AddField(
            model_name='emails',
            name='email_type',
            field=models.CharField(choices=[('0', 'قرار ملاقات'), ('1', 'ارسال صندوق'), ('2', 'اکسل فروش ماهیانه'), ('3', 'تسویه قرارداد بااکسل'), ('4', 'متقاضی و فروشگاه'), ('5', 'تامین کننده جدید')], default='0', max_length=1, verbose_name='نوع ایمیل'),
        ),
    ]
