# Generated by Django 3.2.6 on 2021-09-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0029_alter_emails_email_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='ST',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان ایمل'),
        ),
        migrations.AlterField(
            model_name='emails',
            name='TO',
            field=models.CharField(blank=True, help_text='برای جداسازی از , استفاده کنید', max_length=255, null=True, verbose_name='گیرندگان'),
        ),
        migrations.AlterField(
            model_name='emails',
            name='bcc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رونوشت مخفی'),
        ),
        migrations.AlterField(
            model_name='emails',
            name='cc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رونوشت'),
        ),
    ]
