# Generated by Django 3.2.6 on 2021-09-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0031_emails_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emails',
            table='Emailss',
        ),
    ]
