# Generated by Django 3.2.5 on 2021-09-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0032_alter_emails_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emails',
            name='ET',
            field=models.TextField(blank=True, default='', verbose_name='متن ایمیل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emails',
            name='ST',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='عنوان ایمل'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emails',
            name='TO',
            field=models.CharField(blank=True, default='', help_text='برای جداسازی از , استفاده کنید', max_length=255, verbose_name='گیرندگان'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emails',
            name='bcc',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='رونوشت مخفی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emails',
            name='cc',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='رونوشت'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emails',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='tass/', verbose_name='فایل'),
            preserve_default=False,
        ),
    ]
