# Generated by Django 3.2.7 on 2021-10-11 05:03

import OTP.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0033_auto_20210919_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilecode',
            name='mobile_number',
            field=models.CharField(max_length=11, unique=True, validators=[OTP.models.validate_mobile_number], verbose_name='شماره همراه'),
        ),
    ]
