# Generated by Django 2.2 on 2021-10-02 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0034_auto_20211002_1341'),
        ('OTP', '0034_auto_20210929_1134'),
    ]

    operations = [
    ]
