# Generated by Django 3.2.7 on 2021-10-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0034_alter_mobilecode_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetext',
            name='status',
            field=models.BooleanField(choices=[(True, 'ارسال پیامک'), (False, 'عدم ارسال پیامک')], default=False, verbose_name='حالت ارسال'),
        ),
        migrations.AddField(
            model_name='messagetext',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='عنوان بسته'),
        ),
    ]
