# Generated by Django 2.2 on 2021-10-11 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0035_merge_20211002_1442'),
        ('OTP', '0034_alter_mobilecode_mobile_number'),
    ]

    operations = [
    ]
