# Generated by Django 3.2.7 on 2021-10-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0035_auto_20211019_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetext',
            name='status',
            field=models.BooleanField(choices=[(True, 'ارسال '), (False, 'عدم ارسال ')], default=False, verbose_name='حالت ارسال'),
        ),
    ]
