# Generated by Django 2.2 on 2020-06-08 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('contract', '0002_contract_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier', verbose_name='تأمین کننده'),
        ),
        migrations.AddField(
            model_name='contract',
            name='vcc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contract.vcc', verbose_name=' کارت مجازی'),
        ),
    ]
