# Generated by Django 2.2 on 2020-06-16 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_auto_20200608_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='vcc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.vcc', verbose_name=' کارت مجازی'),
        ),
    ]
