# Generated by Django 2.2 on 2020-06-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_auto_20200620_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='شماره قرارداد'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_fullname',
            field=models.CharField(default='', max_length=50, verbose_name='نام کامل متقاضی'),
        ),
    ]
