# Generated by Django 2.2 on 2020-06-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_auto_20200620_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='net_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ فاکتور'),
            preserve_default=False,
        ),
    ]
