# Generated by Django 3.0.5 on 2020-06-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_auto_20200622_0120'),
        ('contract', '0008_auto_20200622_0115'),
    ]

    operations = [
    ]
