# Generated by Django 3.0.7 on 2020-07-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_auto_20200622_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='appoint_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name=' زمان قرارملاقات'),
        ),
    ]
