# Generated by Django 3.0.7 on 2020-09-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_contract_appoint_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='appoint_time',
            field=models.DateTimeField(blank=True, null=True, unique=True, verbose_name=' زمان قرارملاقات'),
        ),
    ]
