# Generated by Django 3.0.5 on 2020-07-06 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_contract_appoint_time'),
        ('contract', '0009_merge_20200627_1626'),
    ]

    operations = [
    ]
