# Generated by Django 3.0.5 on 2020-09-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_auto_20200912_1713'),
        ('contract', '0010_merge_20200706_2242'),
    ]

    operations = [
    ]
