# Generated by Django 3.0.5 on 2020-09-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_contract_type'),
        ('contract', '0011_merge_20200912_1902'),
    ]

    operations = [
    ]
