# Generated by Django 2.2 on 2020-12-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_auto_20201109_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره قرارداد'),
        ),
    ]
