# Generated by Django 3.0.5 on 2020-11-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0012_auto_20201109_1649'),
        ('contract', '0012_merge_20200924_1329'),
    ]

    operations = [
    ]
