# Generated by Django 2.2 on 2020-12-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_auto_20201216_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('0', 'تأیید نشده'), ('1', ' تایید دریافت پیش پرداخت درحال عقد قرارداد'), ('2', ' تایید قرارداد و ارسال کالا'), ('3', 'تسویه با فروشگاه'), ('4', 'پرداخت اقساط توسط متقاضی'), ('5', 'تسویه نهایی اقساط'), ('6', 'تحویل مدارک به متقاضی'), ('7', 'انصراف متقاضی')], default='0', max_length=1, verbose_name='وضعیت قراردادی'),
        ),
    ]
