# Generated by Django 2.2 on 2020-12-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_auto_20201217_0016'),
        ('contract', '0013_merge_20201109_1946'),
    ]

    operations = [
    ]
