# Generated by Django 2.2 on 2020-12-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_auto_20201217_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='customer_check_factor',
            field=models.FloatField(default=1.1, verbose_name='ضریب چک متقاضی'),
        ),
        migrations.AddField(
            model_name='contract',
            name='surety_check_factor',
            field=models.FloatField(default=1.5, verbose_name='ضریب چک ضامن'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('0', 'تأیید نشده'), ('1', ' تایید دریافت پیش پرداخت درحال عقد قرارداد'), ('2', ' تایید قرارداد و ارسال کالا'), ('3', 'تسویه با فروشگاه'), ('4', 'پرداخت اقساط توسط متقاضی'), ('5', 'تسویه متقاضی و تحویل مدارک'), ('7', 'انصراف متقاضی')], default='0', max_length=1, verbose_name='وضعیت قراردادی'),
        ),
    ]
