# Generated by Django 2.2 on 2020-12-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_auto_20201221_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='Type',
            field=models.CharField(choices=[('0', 'نوع ۱( محاسبات طبق اکسل)'), ('1', 'نوع ۲(محاسبات irr)')], default='1', max_length=1, verbose_name='نوع قرارداد'),
        ),
    ]
