# Generated by Django 2.2 on 2020-12-23 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0015_auto_20201221_1606'),
        ('contract', '0015_merge_20201217_0018'),
    ]

    operations = [
    ]
