# Generated by Django 2.2 on 2020-12-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_auto_20201231_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcc',
            name='status',
            field=models.CharField(choices=[('0', 'آزاد'), ('1', 'مصرف شده'), ('2', 'در حال استفاده')], default='0', max_length=1, verbose_name='وضعیت'),
        ),
    ]
