# Generated by Django 2.2 on 2020-12-30 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_merge_20201223_1528'),
        ('contract', '0017_auto_20201231_0043'),
    ]

    operations = [
    ]
