# Generated by Django 2.2 on 2020-12-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_vcc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='pay_day',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='روز پرداخت قسط'),
        ),
    ]
