# Generated by Django 2.2 on 2021-01-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_merge_20201231_0120'),
        ('contract', '0019_contract_pay_day'),
    ]

    operations = [
    ]
