# Generated by Django 2.2 on 2021-01-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0019_contract_pay_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vcc',
            options={'verbose_name': 'کارت بانکی', 'verbose_name_plural': 'وصول مطالبات'},
        ),
    ]
