# Generated by Django 2.2 on 2021-01-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_merge_20210101_2022'),
        ('contract', '0020_auto_20210101_2037'),
    ]

    operations = [
    ]
