# Generated by Django 2.2 on 2021-01-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0020_auto_20210101_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='face_net_amount',
            field=models.PositiveIntegerField(default=0, help_text='ریال', verbose_name='مبلغ فاکتور ظاهری'),
            preserve_default=False,
        ),
    ]
