# Generated by Django 2.2 on 2021-01-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0021_contract_face_net_amount'),
        ('contract', '0021_merge_20210101_2051'),
    ]

    operations = [
    ]
