# Generated by Django 2.2 on 2021-01-31 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0023_auto_20210130_2232'),
        ('contract', '0022_merge_20210126_1735'),
    ]

    operations = [
    ]
