# Generated by Django 2.2 on 2021-01-31 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0024_merge_20210131_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='face_net_amount',
            field=models.PositiveIntegerField(blank=True, help_text='ریال', verbose_name='مبلغ فاکتور ظاهری'),
        ),
    ]
