# Generated by Django 2.2 on 2021-01-31 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0024_merge_20210131_0138'),
        ('contract', '0025_auto_20210131_0355'),
    ]

    operations = [
    ]
