# Generated by Django 2.2 on 2021-02-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0027_auto_20210201_1412'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractsuretys',
            options={'verbose_name': 'ضمانت', 'verbose_name_plural': 'ضمانت'},
        ),
    ]
