# Generated by Django 2.2 on 2021-03-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0028_auto_20210202_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcc',
            name='faramiran_rank',
            field=models.TextField(blank=True, verbose_name='رتبه فرامیران'),
        ),
    ]
