# Generated by Django 2.2 on 2021-04-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0029_vcc_faramiran_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcc',
            name='instalment_amount',
            field=models.IntegerField(default=0, verbose_name='مبلغ قسط'),
        ),
        migrations.AlterField(
            model_name='vcc',
            name='faramiran_rank',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
