# Generated by Django 2.2 on 2021-03-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0029_vcc_faramiran_rank'),
        ('contract', '0026_merge_20210131_0400'),
    ]

    operations = [
    ]
