# Generated by Django 2.2 on 2021-04-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0031_auto_20210404_1501'),
        ('contract', '0031_auto_20210404_1254'),
    ]

    operations = [
    ]
