# Generated by Django 2.2 on 2021-04-28 10:34

import contract.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0032_auto_20210405_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='send_to_coffer',
            field=models.BooleanField(choices=[(True, 'ارسال شده'), (False, 'ارسال نشده')], default=False, verbose_name='وضعیت ارسال به صندوق'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='company_gain_rate',
            field=models.FloatField(blank=True, validators=[contract.models.validate_rate], verbose_name='کارمزد شرکت'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='discount',
            field=models.FloatField(blank=True, validators=[contract.models.validate_rate], verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='financial_source_rate',
            field=models.FloatField(blank=True, validators=[contract.models.validate_rate], verbose_name='نرخ تسهیلات'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='investor_gain_rate',
            field=models.FloatField(blank=True, validators=[contract.models.validate_rate], verbose_name='کارمزد بازاریاب'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='share_rate',
            field=models.FloatField(blank=True, validators=[contract.models.validate_rate], verbose_name='  سهم شرکت از ضمانت نامه'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='warranty_gain_rate',
            field=models.FloatField(blank=True, validators=[contract.models.validate_rate], verbose_name='کارمزد صدور ضمانت نامه'),
        ),
    ]
