# Generated by Django 2.2 on 2021-04-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0032_merge_20210404_1513'),
        ('contract', '0032_auto_20210405_1240'),
    ]

    operations = [
    ]
