# Generated by Django 2.2 on 2021-04-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0033_auto_20210428_1504'),
        ('contract', '0033_merge_20210405_1554'),
    ]

    operations = [
    ]
