# Generated by Django 2.2 on 2021-04-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0034_merge_20210428_1607'),
        ('contract', '0034_auto_20210428_1659'),
    ]

    operations = [
    ]
