# Generated by Django 2.2 on 2021-05-01 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0030_merge_20210327_1124'),
        ('contract', '0035_merge_20210428_1713'),
    ]

    operations = [
    ]
