# Generated by Django 2.2 on 2021-06-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0038_contractsuretys_cust'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractsuretys',
            name='surt',
        ),
    ]
