# Generated by Django 2.2 on 2021-06-16 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0039_remove_contractsuretys_surt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractsuretys',
            old_name='cust',
            new_name='surt',
        ),
    ]
