# Generated by Django 2.2 on 2021-06-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0040_auto_20210616_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeVCC',
            fields=[
            ],
            options={
                'verbose_name': 'مدیریت کارت',
                'verbose_name_plural': 'مدیریت کارتها',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contract.vcc',),
        ),
        migrations.AlterField(
            model_name='contract',
            name='vcc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.FreeVCC', verbose_name=' کارت مجازی'),
        ),
    ]
