# Generated by Django 2.2 on 2021-06-21 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0041_auto_20210621_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='vcc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.vcc', verbose_name=' کارت مجازی'),
        ),
    ]
