# Generated by Django 2.2 on 2021-08-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0045_contract_contract_permission_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FreeVCC',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='vcc_free',
        ),
    ]
