# Generated by Django 2.2 on 2021-08-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0046_auto_20210823_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='vcc_busy',
            fields=[
            ],
            options={
                'verbose_name': 'کارت بانکی',
                'verbose_name_plural': 'وصول مطالبات',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contract.vcc',),
        ),
        migrations.CreateModel(
            name='vcc_free',
            fields=[
            ],
            options={
                'verbose_name': 'کارت بانکی آزاد',
                'verbose_name_plural': 'کارت های بانکی آزاد',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('contract.vcc',),
        ),
    ]
