# Generated by Django 2.2 on 2021-08-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0047_vcc_busy_vcc_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_permission_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ صدور مجوز قرارداد'),
        ),
    ]
