# Generated by Django 3.2.6 on 2021-09-11 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0009_auto_20210813_1952'),
        ('contract', '0049_auto_20210901_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcc',
            name='coffer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.coffer', verbose_name='صندوق'),
        ),
    ]
