# Generated by Django 3.2.6 on 2021-09-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0050_vcc_coffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcc',
            name='crime_status',
            field=models.CharField(choices=[('0', 'نامعلوم'), ('1', 'بخشیده شده'), ('2', 'پرداخت')], default='0', max_length=1, verbose_name=' وضعیت بخشودگی جرم'),
        ),
    ]
