# Generated by Django 3.2.6 on 2021-09-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0051_vcc_crime_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vcc',
            name='crime_status',
        ),
        migrations.AddField(
            model_name='vcc',
            name='new_status',
            field=models.CharField(choices=[('0', 'نامعلوم'), ('1', 'بخشوده'), ('2', 'پرداخت')], default='0', max_length=1, verbose_name=' وضعیت بخشودگی جریمه'),
        ),
    ]
