version: '3.3'


services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/backend
      - test_static_volume:/backend/static
      - test_media_volume:/backend/media
    restart: always
    ports:
      - "8000:8000"
    networks:
      - test_network
      - nginx_network
    depends_on:
      - test_postgresql

  test_postgresql:
      image: postgres:10
      container_name: test_postgresql
      volumes:
        - test_postgresql:/var/lib/postgresql/data
      restart: always
      env_file: .env
      ports:
        - "5432:5432"
      networks:
        - test_network




volumes:
  test_postgresql:
    external: true
  test_static_volume:
    external: true
  test_media_volume:
    external: true
networks:
  test_network:
    external: true
  nginx_network:
    external: true