# Generated by Django 2.2 on 2020-06-08 18:40

from django.db import migrations, models
import django.db.models.deletion
import document.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='surety_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mellicard_front', models.ImageField(upload_to=document.models.surety_directory_path, verbose_name='روی کارت ملی')),
                ('mellicard_behind', models.ImageField(upload_to=document.models.surety_directory_path, verbose_name='پشت کارت ملی')),
                ('identity_firstpage', models.ImageField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name='صفحه اول شناسنامه')),
                ('identity_description', models.ImageField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name='توضیحات شناسنامه')),
                ('house_evidence', models.ImageField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name='مدرک سکونت')),
                ('consent_form', models.ImageField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name='رضایت نامه اعتبار سنجی')),
                ('receipt_of_deposit', models.ImageField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name='رسید هزینه ی اعتبارسنجی')),
                ('credit_rate', models.FileField(upload_to=document.models.surety_directory_path, verbose_name='خروجی سایت اعتبار سنجی')),
                ('caccount_turnover', models.ImageField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name='گردش حساب جاری')),
                ('oaccount_turnover', models.ImageField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name=' گردش حساب اصلی یا فیش حقوقی مهردار')),
                ('marketing_license', models.ImageField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name='جواز کسب')),
                ('employment_certification', models.ImageField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name='گواهی اشتغال')),
                ('recommendation', models.ImageField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name='معرفی نامه سازمان')),
                ('surety', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.surety', verbose_name='ضامن')),
            ],
            options={
                'verbose_name': 'مدارک ضامن',
                'verbose_name_plural': 'مدارک ضامنین',
            },
        ),
        migrations.CreateModel(
            name='customer_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mellicard_front', models.ImageField(upload_to=document.models.customer_directory_path, verbose_name='روی کارت ملی')),
                ('mellicard_behind', models.ImageField(upload_to=document.models.customer_directory_path, verbose_name='پشت کارت ملی')),
                ('identity_firstpage', models.ImageField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='صفحه اول شناسنامه')),
                ('identity_description', models.ImageField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='توضیحات شناسنامه')),
                ('house_evidence', models.ImageField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='مدرک سکونت')),
                ('consent_form', models.ImageField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='رضایت نامه اعتبار سنجی')),
                ('receipt_of_deposit', models.ImageField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='رسید هزینه ی اعتبارسنجی')),
                ('credit_rate', models.FileField(upload_to=document.models.customer_directory_path, verbose_name='خروجی سایت اعتبار سنجی')),
                ('caccount_turnover', models.ImageField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='گردش حساب جاری')),
                ('oaccount_turnover', models.ImageField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name=' گردش حساب اصلی یا فیش حقوقی مهردار')),
                ('marketing_license', models.ImageField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='جواز کسب')),
                ('employment_certification', models.ImageField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='گواهی اشتغال')),
                ('recommendation', models.ImageField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='معرفی نامه سازمان')),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='متقاضی')),
            ],
            options={
                'verbose_name': 'مدارک متقاضی',
                'verbose_name_plural': 'مدارک متقاضیان',
            },
        ),
        migrations.CreateModel(
            name='contract_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_contract', models.ImageField(null=True, upload_to=document.models.contract_directory_path, verbose_name='قرارداد امضا شده')),
                ('customer_check', models.ImageField(null=True, upload_to=document.models.contract_directory_path, verbose_name='چک متقاضی')),
                ('surety_check1', models.ImageField(blank=True, null=True, upload_to=document.models.contract_directory_path, verbose_name='۱چک ضامن')),
                ('surety_check2', models.ImageField(blank=True, null=True, upload_to=document.models.contract_directory_path, verbose_name='چک ضامن۲')),
                ('pre_invoice', models.ImageField(blank=True, null=True, upload_to=document.models.contract_directory_path, verbose_name='پیش فاکتور')),
                ('final_invoice', models.ImageField(blank=True, null=True, upload_to=document.models.contract_directory_path, verbose_name='فاکتور نهایی')),
                ('downpayment_receipt', models.ImageField(blank=True, null=True, upload_to=document.models.contract_directory_path, verbose_name='فیش واریز پیش پرداخت')),
                ('contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contract.contract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': ' مدارک قرارداد',
                'verbose_name_plural': ' مدارک قراردادها',
            },
        ),
    ]
