# Generated by Django 2.2 on 2020-06-16 10:58

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_document',
            name='marketing_license',
        ),
        migrations.RemoveField(
            model_name='customer_document',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='surety_document',
            name='marketing_license',
        ),
        migrations.RemoveField(
            model_name='surety_document',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='customer_document',
            name='complemental',
            field=models.ImageField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='مدارک تکمیلی'),
        ),
        migrations.AddField(
            model_name='customer_document',
            name='postalcode_evidence',
            field=models.ImageField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='گواهی کد پستی'),
        ),
        migrations.AddField(
            model_name='surety_document',
            name='complemental',
            field=models.ImageField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name='مدارک تکمیلی'),
        ),
        migrations.AddField(
            model_name='surety_document',
            name='postalcode_evidence',
            field=models.ImageField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='گواهی کد پستی'),
        ),
        migrations.AlterField(
            model_name='customer_document',
            name='employment_certification',
            field=models.ImageField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='گواهی اشتغال-جواز کسب'),
        ),
        migrations.AlterField(
            model_name='surety_document',
            name='employment_certification',
            field=models.ImageField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name='گواهی اشتغال -جواز کسب'),
        ),
    ]
