# Generated by Django 3.0.7 on 2020-06-27 11:34

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20200616_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_document',
            name='consent_form',
        ),
        migrations.RemoveField(
            model_name='surety_document',
            name='consent_form',
        ),
        migrations.AddField(
            model_name='customer_document',
            name='recommendation',
            field=models.FileField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='معرفی نامه سازمان'),
        ),
        migrations.AddField(
            model_name='surety_document',
            name='recommendation',
            field=models.FileField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name='معرفی نامه سازمان'),
        ),
        migrations.AlterField(
            model_name='customer_document',
            name='postalcode_evidence',
            field=models.FileField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='گواهی کد پستی'),
        ),
        migrations.AlterField(
            model_name='surety_document',
            name='postalcode_evidence',
            field=models.FileField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name='گواهی کد پستی'),
        ),
    ]
