# Generated by Django 3.0.7 on 2020-10-12 08:06

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20200912_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_document',
            name='mellicard_behind',
            field=models.FileField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='پشت کارت ملی'),
        ),
        migrations.AlterField(
            model_name='surety_document',
            name='mellicard_behind',
            field=models.FileField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name='پشت کارت ملی'),
        ),
    ]
