# Generated by Django 2.2 on 2020-12-30 20:24

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_auto_20201223_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_document',
            name='cust_c',
            field=models.FileField(blank=True, null=True, upload_to=document.models.contract_directory_path, verbose_name='خلاص قرارداد مشتری'),
        ),
        migrations.AddField(
            model_name='contract_document',
            name='supp_c',
            field=models.FileField(blank=True, null=True, upload_to=document.models.contract_directory_path, verbose_name='خلاصه قرارداد فروشگاه'),
        ),
    ]
