# Generated by Django 2.2 on 2021-01-04 19:16

from django.db import migrations, models
import document.models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_auto_20201230_2354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_document',
            name='receipt_of_deposit',
        ),
        migrations.RemoveField(
            model_name='surety_document',
            name='receipt_of_deposit',
        ),
        migrations.AddField(
            model_name='customer_document',
            name='sayyad_check',
            field=models.FileField(blank=True, null=True, upload_to=document.models.customer_directory_path, verbose_name='چک صیاد'),
        ),
        migrations.AddField(
            model_name='surety_document',
            name='sayyad_check',
            field=models.FileField(blank=True, null=True, upload_to=document.models.surety_directory_path, verbose_name='چک صیاد'),
        ),
    ]
