# Generated by Django 2.2 on 2021-08-27 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_auto_20210508_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_document',
            name='contract',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='contract.contract', verbose_name='قرارداد'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_document',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='متقاضی'),
            preserve_default=False,
        ),
    ]
