# Generated by Django 2.2 on 2020-06-15 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surety',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suretys', to='customer.customer', verbose_name='مضمون عنه'),
        ),
    ]
