# Generated by Django 2.2 on 2020-06-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20200615_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='job_class',
            field=models.CharField(choices=[('0', 'دولتی'), ('1', 'آزاد'), ('2', 'مستمری بگیر')], default='0', max_length=1, verbose_name='حوزه شغلی'),
        ),
    ]
