# Generated by Django 2.2 on 2020-06-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_job_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surety',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='surety',
            name='job_class',
            field=models.CharField(choices=[('0', 'دولتی'), ('1', 'آزاد'), ('2', 'مستمری بگیر')], default='0', max_length=1, verbose_name='حوزه شغلی'),
        ),
        migrations.AddField(
            model_name='surety',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='نام خانوادگی'),
        ),
    ]
