# Generated by Django 2.2 on 2020-06-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200616_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surety',
            name='family_name',
        ),
    ]
