# Generated by Django 3.0.7 on 2020-08-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_surety_family_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='level',
            field=models.CharField(choices=[('0', 'مشخص نشده'), ('1', 'سطح ۱'), ('2', 'سطح ۲'), ('3', 'سطح ۳')], default='0', max_length=1, verbose_name='سطح تسهیلات'),
        ),
    ]
