# Generated by Django 3.0.7 on 2020-08-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20200822_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='level',
            field=models.CharField(choices=[('0', 'مشخص نشده'), ('1', 'سطح ۱(بدون ضامن)'), ('2', 'سطح ۲(یک ضامن)'), ('3', 'سطح ۳(دو ضامن)')], default='0', max_length=1, verbose_name='سطح تسهیلات'),
        ),
    ]
