# Generated by Django 3.0.7 on 2020-10-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20200822_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='estimate_income',
            field=models.IntegerField(default=0, help_text='ریال', verbose_name='حدود درآمد ماهانه'),
        ),
        migrations.AlterField(
            model_name='surety',
            name='estimate_income',
            field=models.IntegerField(default=0, help_text='ریال', verbose_name='حدود درآمد ماهانه'),
        ),
    ]
