# Generated by Django 3.0.7 on 2020-11-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20201019_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='job_class',
            field=models.CharField(choices=[('0', 'حقوق بگیر'), ('1', 'آزاد'), ('2', 'مستمری بگیر')], default='0', max_length=1, verbose_name='حوزه شغلی'),
        ),
        migrations.AlterField(
            model_name='surety',
            name='job_class',
            field=models.CharField(choices=[('0', 'حقوق بگیر'), ('1', 'آزاد'), ('2', 'مستمری بگیر')], default='0', max_length=1, verbose_name='حوزه شغلی'),
        ),
    ]
