# Generated by Django 2.2 on 2020-11-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20201115_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='surety',
            name='gender',
            field=models.CharField(choices=[('m', 'آقای'), ('f', 'خانم')], default='m', max_length=1, verbose_name='جنسیت'),
        ),
    ]
