# Generated by Django 2.2 on 2020-12-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_surety_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='level',
            field=models.CharField(choices=[('0', 'مشخص نشده'), ('1', 'سطح ۱'), ('2', 'سطح ۲'), ('3', 'سطح ۳')], default='0', max_length=1, verbose_name='سطح تسهیلات'),
        ),
    ]
