# Generated by Django 2.2 on 2020-12-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20201217_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('0', 'درحال بررسی'), ('1', 'تایید شده'), ('2', 'رد شده'), ('3', 'تایید مشروط'), ('4', 'انصراف متقاضی')], default='0', max_length=1, verbose_name='وضعیت اعتباری'),
        ),
    ]
