# Generated by Django 2.2 on 2021-01-18 12:22

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_auto_20210104_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surety',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=11, validators=[customer.models.validate_phone_number], verbose_name='شماره منزل'),
        ),
        migrations.AlterField(
            model_name='surety',
            name='workplace_number',
            field=models.CharField(blank=True, default='', max_length=11, validators=[customer.models.validate_phone_number], verbose_name='شماره ضروری'),
        ),
    ]
