# Generated by Django 2.2 on 2021-04-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20210403_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('00', 'در انتظار تکمیل مدارک'), ('0', 'درحال بررسی'), ('1', 'تایید شده'), ('2', 'رد شده'), ('3', 'تایید مشروط'), ('4', 'انصراف متقاضی'), ('5', 'نقص مدارک'), ('6', 'انقضای رتبه اعتباری')], default='0', max_length=2, verbose_name='وضعیت اولیه متقاضی'),
        ),
    ]
