# Generated by Django 2.2 on 2021-04-21 10:26

import customer.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20210417_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, max_length=20, verbose_name='نسبت')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='نام خانوادگی')),
                ('mobile_number', models.CharField(max_length=11, unique=True, validators=[customer.models.validate_mobile_number], verbose_name='شماره همراه')),
                ('melli_code', models.CharField(blank=True, max_length=10, validators=[customer.models.validate_melli_code], verbose_name='کد ملی')),
                ('is_mine', models.CharField(choices=[('0', 'قرارداد اجاره بنام خودم است'), ('1', 'قرارداد اجاره بنام خودم نیست')], default='0', max_length=1, verbose_name='طرف قرارداد')),
                ('rental_rate', models.IntegerField(default=0, help_text='میلیون ریال', verbose_name='میزان اجاره')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید قرارداد')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='متقاضی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonalHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, max_length=20, verbose_name='نسبت')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='نام خانوادگی')),
                ('mobile_number', models.CharField(max_length=11, unique=True, validators=[customer.models.validate_mobile_number], verbose_name='شماره همراه')),
                ('melli_code', models.CharField(blank=True, max_length=10, validators=[customer.models.validate_melli_code], verbose_name='کد ملی')),
                ('document_type', models.CharField(choices=[('0', 'تک برگ'), ('1', 'منگوله دار')], default='0', max_length=1, verbose_name='نوع سند')),
                ('is_owner', models.CharField(choices=[('0', 'مالک نیستم'), ('1', 'مالک هستم')], default='0', max_length=1, verbose_name=' مالک')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='متقاضی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='عنوان سازمانی')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='متقاضی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Financial_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_amount', models.IntegerField(help_text='ریال', verbose_name='مبلغ سبد خرید')),
                ('number_of_instalment', models.IntegerField(default=12, verbose_name='تعداد اقساط')),
                ('downpayment', models.IntegerField(blank=True, help_text='ریال', verbose_name='پیش پرداخت')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='متقاضی')),
            ],
        ),
        migrations.CreateModel(
            name='check_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_check', models.CharField(choices=[('0', 'خودم چک ندارم'), ('1', 'خودم چک دارم')], default='0', max_length=1, verbose_name='داشتن چک')),
                ('sayyad_number', models.CharField(max_length=16, unique=True, verbose_name='شماره صیاد چک')),
                ('city', models.CharField(blank=True, default='', max_length=30, verbose_name='شهر محل صدور')),
                ('branch_name', models.CharField(default='', max_length=30, verbose_name='نام شعبه')),
                ('branch_code', models.CharField(default='', max_length=10, verbose_name='کد شعبه')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='متقاضی')),
                ('surety', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.surety', verbose_name='ضامن')),
            ],
        ),
    ]
