# Generated by Django 2.2 on 2021-04-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_check_information_financial_information_organizationhome_personalhome_rentalhome'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='home_type',
            field=models.CharField(choices=[('0', 'شخصی'), ('1', 'سازمانی'), ('2', 'استیجاری')], default='0', max_length=1, verbose_name='وضعیت ملکی'),
        ),
    ]
