# Generated by Django 2.2 on 2021-04-26 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_customer_home_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='check_information',
            options={'verbose_name': 'اطلاعات چک', 'verbose_name_plural': 'اطلاعات چک ها'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'همراه', 'verbose_name_plural': 'همراه ها'},
        ),
        migrations.AlterModelOptions(
            name='financial_information',
            options={'verbose_name': 'اطلاعات مالی', 'verbose_name_plural': 'اطلاعات مالی'},
        ),
        migrations.AlterModelOptions(
            name='organizationhome',
            options={'verbose_name': 'ملک سازمانی', 'verbose_name_plural': 'ملک های سازمانی'},
        ),
        migrations.AlterModelOptions(
            name='personalhome',
            options={'verbose_name': 'ملک شخصی', 'verbose_name_plural': 'ملک های شخصی'},
        ),
        migrations.AlterModelOptions(
            name='rentalhome',
            options={'verbose_name': 'ملک اجاره ای', 'verbose_name_plural': 'ملک های اجاره ای'},
        ),
        migrations.AddField(
            model_name='customer',
            name='again_purchase',
            field=models.BooleanField(choices=[(False, 'نمیتواند خرید مجدد بکند'), (True, 'میتواند خرید مجدد بکند')], default=True, verbose_name='توانایی خرید مجدد'),
        ),
        migrations.AddField(
            model_name='customer',
            name='surety_permission',
            field=models.BooleanField(choices=[(False, 'نمیتواند ضامن باشد'), (True, 'میتواند ضامن باشد')], default=True, verbose_name='توانایی ضامن شدن'),
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surety_order', models.CharField(choices=[('1', 'ضامن اول است'), ('0', 'ضامن دوم است')], default='1', max_length=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_suretys', to='customer.customer', verbose_name='متقاضی')),
                ('surety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_customers', to='customer.customer', verbose_name='ضامن')),
            ],
        ),
    ]
