# Generated by Django 2.2 on 2021-04-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_auto_20210426_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='credit_rank',
            field=models.CharField(blank=True, max_length=1000, verbose_name='شرح وضعیت'),
        ),
    ]
