# Generated by Django 2.2 on 2021-04-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_merge_20210404_1513'),
        ('customer', '0025_auto_20210426_1557'),
    ]

    operations = [
    ]
