# Generated by Django 2.2 on 2021-04-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_auto_20210428_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guarantee',
            options={'verbose_name': 'ضامن', 'verbose_name_plural': 'ضامنها'},
        ),
        migrations.AddField(
            model_name='customer',
            name='job_status',
            field=models.CharField(choices=[('0', 'قرارداد موقت (با مدت معین)'), ('1', 'قرارداد غیرموقت (دائم)'), ('2', 'بدون قرارداد'), ('3', 'با پروانه کسب یا اجاره نامه تجاری به نام'), ('4', 'بدون پروانه کسب یا اجاره نامه تجاری به نام'), ('5', 'کارکنان رسمی دولت'), ('6', 'استخدام پیمانی'), ('7', 'کارکنان خدماتی'), ('8', 'سازمان تامین اجتماعی'), ('9', 'سازمان بازنشستگی کشوری'), ('10', 'سازمان بازنشستگی نیروهای مسلح'), ('11', 'رسمی'), ('12', 'سایر')], default='0', max_length=2, verbose_name='وضعیت شغلی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='home_type',
            field=models.CharField(choices=[('0', 'شخصی'), ('2', 'استیجاری'), ('1', 'سازمانی')], default='0', max_length=1, verbose_name='وضعیت ملکی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='job_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='نشانی محل کار'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='job_class',
            field=models.CharField(choices=[('3', 'خصوصی'), ('1', 'آزاد'), ('0', 'دولتی'), ('4', 'نیروهای مسلح'), ('5', 'بازنشسته'), ('2', 'مستمری بگیر')], default='0', max_length=1, verbose_name='حوزه شغلی'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='job_phone_number',
            field=models.CharField(blank=True, max_length=11, verbose_name='شماره تماس محل کار'),
        ),
        migrations.AlterField(
            model_name='family',
            name='Type',
            field=models.CharField(choices=[('0', 'پدر'), ('1', 'مادر'), ('2', 'برادر'), ('3', 'خواهر'), ('4', 'همسر')], default='0', max_length=1, verbose_name='نسبت با متقاضی'),
        ),
        migrations.AlterField(
            model_name='family',
            name='phone_number_description',
            field=models.CharField(blank=True, max_length=20, verbose_name='عنوان تلفن ثابت'),
        ),
        migrations.AlterField(
            model_name='financial_information',
            name='cart_amount',
            field=models.IntegerField(help_text='میلیون ریال', verbose_name='مبلغ سبد خرید'),
        ),
        migrations.AlterField(
            model_name='financial_information',
            name='downpayment',
            field=models.IntegerField(blank=True, help_text='میلیون ریال', verbose_name='پیش پرداخت'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='surety_order',
            field=models.CharField(choices=[('1', 'ضامن اول'), ('0', 'ضامن دوم')], default='1', max_length=1, verbose_name='ترتیب ضامن'),
        ),
        migrations.AlterField(
            model_name='surety',
            name='job_class',
            field=models.CharField(choices=[('3', 'خصوصی'), ('1', 'آزاد'), ('0', 'دولتی'), ('4', 'نیروهای مسلح'), ('5', 'بازنشسته'), ('2', 'مستمری بگیر')], default='0', max_length=1, verbose_name='حوزه شغلی'),
        ),
        migrations.AlterUniqueTogether(
            name='guarantee',
            unique_together={('customer', 'surety'), ('customer', 'surety_order')},
        ),
    ]
