# Generated by Django 2.2 on 2021-04-28 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_auto_20210428_1425'),
        ('customer', '0026_merge_20210426_1624'),
    ]

    operations = [
    ]
