# Generated by Django 2.2 on 2021-04-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_auto_20210428_1659'),
        ('customer', '0027_merge_20210428_1607'),
    ]

    operations = [
    ]
