# Generated by Django 2.2 on 2021-05-08 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_auto_20210428_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='description',
            new_name='cust_description',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
