# Generated by Django 2.2 on 2021-05-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_auto_20210511_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_rank',
            field=models.TextField(blank=True, verbose_name='شرح وضعیت'),
        ),
    ]
