# Generated by Django 2.2 on 2021-05-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_auto_20210511_1254'),
        ('customer', '0028_merge_20210428_1713'),
    ]

    operations = [
    ]
