# Generated by Django 2.2 on 2021-05-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_auto_20210510_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='surety_order',
            field=models.CharField(choices=[('2', 'ضامن سوم'), ('1', 'ضامن اول'), ('0', 'ضامن دوم')], default='1', max_length=1, verbose_name='ترتیب ضامن'),
        ),
    ]
