# Generated by Django 2.2 on 2021-06-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_auto_20210526_1512'),
        ('customer', '0030_auto_20210531_1203'),
    ]

    operations = [
    ]
