# Generated by Django 2.2 on 2021-06-02 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_auto_20210526_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_information',
            name='surety',
        ),
    ]
