# Generated by Django 2.2 on 2021-06-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_merge_20210602_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_rank',
            field=models.CharField(blank=True, max_length=1000, verbose_name='شرح وضعیت'),
        ),
    ]
