# Generated by Django 2.2 on 2021-06-02 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_auto_20210602_1009'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guarantee',
            unique_together=set(),
        ),
    ]
