# Generated by Django 2.2 on 2021-06-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_auto_20210602_1043'),
        ('customer', '0032_remove_check_information_surety'),
    ]

    operations = [
    ]
