# Generated by Django 2.2 on 2021-06-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0035_merge_20210602_1446'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guarantee',
            unique_together={('customer', 'surety')},
        ),
    ]
