# Generated by Django 2.2 on 2021-06-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_auto_20210602_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='surteys',
            field=models.ManyToManyField(through='customer.Guarantee', to='customer.customer'),
        ),
    ]
