# Generated by Django 2.2 on 2021-06-14 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_customer_surteys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial_information',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial', to='customer.customer', verbose_name='متقاضی'),
        ),
    ]
