# Generated by Django 2.2 on 2021-06-14 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_auto_20210614_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalhome',
            name='page_number',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='شماره صفحه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personalhome',
            name='real_state_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='شماره دفتر املاک'),
        ),
        migrations.AddField(
            model_name='personalhome',
            name='unique_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره یکتا'),
        ),
        migrations.AddField(
            model_name='rentalhome',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='کد رهگیری'),
        ),
        migrations.AlterField(
            model_name='check_information',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkinfo', to='customer.customer', verbose_name='متقاضی'),
        ),
    ]
