# Generated by Django 2.2 on 2021-06-14 14:27

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_auto_20210614_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_information',
            name='sayyad_number',
            field=models.CharField(blank=True, max_length=16, verbose_name='شماره صیاد چک'),
        ),
        migrations.AlterField(
            model_name='family',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, validators=[customer.models.validate_mobile_number], verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='financial_information',
            name='cart_amount',
            field=models.IntegerField(default=0, help_text='میلیون ریال', verbose_name='مبلغ سبد خرید'),
        ),
        migrations.AlterField(
            model_name='organizationhome',
            name='title',
            field=models.CharField(blank=True, max_length=60, verbose_name='عنوان سازمانی'),
        ),
        migrations.AlterField(
            model_name='personalhome',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, validators=[customer.models.validate_mobile_number], verbose_name='شماره همراه'),
        ),
        migrations.AlterField(
            model_name='personalhome',
            name='page_number',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='شماره صفحه'),
        ),
        migrations.AlterField(
            model_name='rentalhome',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, validators=[customer.models.validate_mobile_number], verbose_name='شماره همراه'),
        ),
    ]
