# Generated by Django 2.2 on 2021-08-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_auto_20210614_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='surety_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ صدور ضمانت'),
        ),
    ]
