# Generated by Django 3.2.5 on 2021-09-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_customer_confirmation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationhome',
            options={'verbose_name': 'ملک سازمانی', 'verbose_name_plural': 'وضعیت مسکن:سازمانی'},
        ),
        migrations.AlterModelOptions(
            name='personalhome',
            options={'verbose_name': 'ملک شخصی', 'verbose_name_plural': 'وضعیت مسکن ملکی'},
        ),
        migrations.AlterModelOptions(
            name='rentalhome',
            options={'verbose_name': 'ملک اجاره ای', 'verbose_name_plural': 'وضعیت مسکن:استیجاری'},
        ),
    ]
