# Generated by Django 2.2 on 2020-06-08 18:40

from django.db import migrations, models
import django.db.models.deletion
import supplier.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, verbose_name='لینک کوتاه')),
                ('logo', models.ImageField(null=True, upload_to=supplier.models.logo_directory_path, verbose_name='تصویر')),
                ('order', models.IntegerField(verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, verbose_name='لینک کوتاه')),
                ('order', models.IntegerField(verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='coffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('financial_source_rate', models.FloatField(blank=True, default=0.3, verbose_name='تسهیلات خالص')),
                ('contract_code', models.CharField(max_length=4, unique=True, verbose_name='کد قراردادی')),
            ],
            options={
                'verbose_name': 'صندوق',
                'verbose_name_plural': 'صندوق ها',
            },
        ),
        migrations.CreateModel(
            name='issuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('warranty_gain_rate', models.FloatField(blank=True, default=0, verbose_name='کارمزد صدور ضمانت نامه')),
                ('share_rate', models.FloatField(blank=True, default=0.5, verbose_name=' سهم توسعه')),
            ],
            options={
                'verbose_name': 'صادرکننده ضمانت نامه',
                'verbose_name_plural': 'صادرکنندگان ضمانت نامه',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, verbose_name='لینک کوتاه')),
                ('order', models.IntegerField(verbose_name='ترتیب نمایش')),
                ('image', models.ImageField(null=True, upload_to=supplier.models.product_directory_path, verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'محصول یا خدمت',
                'verbose_name_plural': 'محصولات و خدمات',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30, verbose_name='نشان تأمین کننده')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='نشانی وبگاه')),
                ('phone_number', models.CharField(blank=True, default='', max_length=50, verbose_name='شماره تماس')),
                ('status', models.BooleanField(choices=[(True, 'نمایش داده شود'), (False, 'پیش نویس')], default=False, null=True, verbose_name='وضعیت نمایش')),
                ('Type', models.CharField(choices=[('0', 'اجازه ی تولید قراداد ندارد'), ('1', 'امکان تولید قرارداد دارد')], default='0', max_length=1, verbose_name='سطح دسترسی')),
                ('fcategory', models.CharField(choices=[('0', 'کالا'), ('1', 'خدمات')], default='0', max_length=1, verbose_name='دسته بندی کلی')),
                ('downpayment_rate', models.FloatField(default=0.25, verbose_name=' پیش پرداخت')),
                ('company_gain_rate_one', models.FloatField(blank=True, default=0.02, verbose_name='کارمزد شرکت یک ساله')),
                ('company_gain_rate_two', models.FloatField(blank=True, verbose_name='کارمزد شرکت دو ساله')),
                ('investor_gain_rate', models.FloatField(blank=True, default=0, verbose_name='کارمزد بازاریاب')),
                ('additional_costs', models.IntegerField(default=0, verbose_name='هزینه های اضافی')),
                ('discount', models.FloatField(verbose_name='تخفیف')),
                ('contract_code', models.CharField(max_length=4, unique=True, verbose_name='کد قراردادی')),
                ('accountant_name', models.CharField(default='', max_length=80, verbose_name='نام صاحب حساب')),
                ('account_bank', models.CharField(default='', max_length=40, verbose_name='بانک')),
                ('account_shaba', models.CharField(default='', max_length=40, verbose_name='شماره شبا')),
                ('brands', models.ManyToManyField(blank=True, to='supplier.brand', verbose_name='برندها')),
                ('category', models.ManyToManyField(blank=True, to='supplier.Category', verbose_name='دسته')),
                ('coffer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.coffer', verbose_name='صندوق')),
                ('customer', models.ManyToManyField(blank=True, to='customer.customer', verbose_name='مشتری')),
                ('issuer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.issuer', verbose_name='صادر کننده ضمانت نامه')),
                ('products', models.ManyToManyField(blank=True, to='supplier.Product', verbose_name='محصولات')),
            ],
            options={
                'verbose_name': 'تأمین کننده',
                'verbose_name_plural': 'تأمین کنندگان',
            },
        ),
    ]
