# Generated by Django 2.2 on 2020-06-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='نشانی'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='شهر'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='province',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='استان'),
        ),
    ]
