# Generated by Django 3.0.7 on 2020-11-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_auto_20200616_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='نشانی'),
        ),
    ]
