# Generated by Django 2.2 on 2021-02-28 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_auto_20201115_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffer',
            name='contract_file',
            field=models.FileField(null=True, upload_to='', verbose_name='فایل خام قرارداد'),
        ),
    ]
