# Generated by Django 2.2 on 2021-04-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_coffer_contract_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffer',
            name='financial_source_rate',
            field=models.FloatField(blank=True, default=0.3, verbose_name='نرخ تسهیلات'),
        ),
    ]
