# Generated by Django 2.2 on 2021-05-08 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0006_auto_20210428_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='address',
            new_name='store_address',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='city',
            new_name='store_city',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='phone_number',
            new_name='store_phone_number',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='province',
            new_name='store_province',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='id',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='نماینده'),
        ),
    ]
