# Generated by Django 2.2 on 2021-05-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0007_auto_20210508_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='store_address',
            field=models.TextField(blank=True, default='', verbose_name='نشانی محل کار'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='store_city',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name=' شهر محل کار'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='store_phone_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name=' شماره تماس محل کار'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='store_province',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='استان محل کار'),
        ),
    ]
