# Generated by Django 2.2 on 2021-08-13 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0008_auto_20210510_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bazaryab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85, verbose_name='نام بازاریاب')),
                ('gain_rate', models.FloatField(blank=True, verbose_name='کارمزد بازاریاب')),
            ],
            options={
                'verbose_name': 'بازاریاب',
                'verbose_name_plural': 'بازاریاب ها',
            },
        ),
        migrations.AddField(
            model_name='supplier',
            name='bazaryab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.Bazaryab', verbose_name='بازاریاب'),
        ),
    ]
